package dev.mmauro.malverio

enum class RationedEvent {
    AIRLIFT,
    DATA_TRANSFER,
    DISPERSAL,
    DRASTIC_MEASURES,
    EXTENDED_FORECAST,
    EXTENDED_TIME,
    HIDDEN_STOCKPILE,
    IT_WORKED_THE_FIRST_TIME,
    ONE_QUIET_NIGHT,
    RESILIENT_POPULATION,
    TEAM_BRAVO,
}